services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tyres
      POSTGRES_PASSWORD: tyres
      POSTGRES_DB: tyres
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  meili:
    image: getmeili/meilisearch:v1.6
    environment:
      MEILI_MASTER_KEY: "devmasterkey"
    ports: ["7700:7700"]

  strapi:
    build:
      context: .
      dockerfile: strapi/Dockerfile
    # platform: linux/arm64   # light Node-Alpine build
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: tyres # same physical DB
      DATABASE_SCHEMA: cms # 👈 Strapi will create tables here
      DATABASE_USERNAME: tyres
      DATABASE_PASSWORD: tyres
    ports: ["1337:1337"]
    depends_on: [db]

volumes:
  pgdata:
